services:
  neq-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neq-backend
    restart: unless-stopped
    volumes:
      - .:/app
      - ./neverendingquest.db:/app/neverendingquest.db
    ports:
      - "8357:8357"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_TYPE=sqlite
      - WEB_PORT=8357
    working_dir: /app
    tty: true
    stdin_open: true
